[package]
name = "sito"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs-next = "2.0.0"
rand = "0.9.1"
rustyline = "15.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
